name: Build and Package BendolSort

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: '3.10'}
    - run: pip install PyQt5 Pillow exifread pyinstaller
    
    - name: Build
      run: pyinstaller --noconsole --onefile --name=BendolSort main.py

    # Simpan file hasil build sebagai "artifact" sementara
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BendolSort-${{ matrix.os }}
        path: dist/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-assets
        merge-multiple: true

    - name: Publish to Release
      uses: softprops/action-gh-release@v2
      with:
        files: all-assets/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
